# configs/train_config.yaml

# --- Path Configuration ---
# Root directory for training data (containing -Corrected folders with Images and Labels)
train_data_root: "E:/AAA/MICCAI-Challenge-STSR2025/MICCAI-Challenge-STSR2025-Task2/Train-Labeled"
# Root directory for validation data
val_data_root: "D:/datasets/lz-data/2025-04-15/MICCAI-challenge2025-Taks2/final_split/Validation-Public"
# Root directory for experiment outputs (weights, logs, etc.)
output_dir: "./experiments"


# --- Experiment Configuration ---
# Experiment name (will create a subfolder under output_dir)
# experiment_name: "lower_jaw_registration_v1"
experiment_name: "upper_jaw_registration_v1"

# Jaw type to train: 'lower' or 'upper'
jaw_type: "upper"
# Device to use ('cuda' or 'cpu')
device: "cuda"

# --- Training Hyperparameters ---
epochs: 200
batch_size: 1
learning_rate: 0.0001

# --- Dataset Configuration ---
num_points_stl: 4096        # Number of points sampled from STL mesh
num_points_cbct: 8192       # Number of points sampled from CBCT scan
num_workers: 4              # Number of worker threads for DataLoader

# --- Model Configuration ---
feature_dim: 128            # Feature dimension output by PointNet++