# configs/train_config.yaml

project_name: "cbct_segmentation_baseline_v2"

# 1. Data Settings
data:
  image_dir: "MICCAI-Challenge-STSR2025/MICCAI-Challenge-STSR2025-Task1/Train-Labeled/Images"
  label_dir: "MICCAI-Challenge-STSR2025-Task1/Train-Labeled/Masks"
  

  num_classes: 13
  
  val_split: 0.2
  random_seed: 42
  
  persistent_cache: False
  persistent_cache_dir: "./persistent_cache"
  num_workers: 4

# 2. Preprocessing & Augmentation Settings (MONAI Transforms)
transforms:
  orientation: "RAS"
  spacing: [0.5, 0.5, 0.5]

  intensity_norm:
    a_min: -1000.0
    a_max: 1000.0
    b_min: 0.0
    b_max: 1.0
    clip: True
  
  crop_foreground: True
  
  spatial_crop_size: [32, 32, 32]

  rand_crop_pos_ratio: 0.9
  rand_flip_prob: 0.5
  rand_rotate90_prob: 0.5
  rand_scale_intensity_prob: 0.1
  rand_shift_intensity_prob: 0.1

# 3. Model Settings (SegResNet)
model:
  name: "SegResNet"
  spatial_dims: 3
  in_channels: 1
  out_channels: 13
  init_filters: 16
  blocks_down: [1, 2, 2, 4]
  blocks_up: [1, 1, 1]
  dropout_prob: 0.1

# 4. Training Settings
training:
  device: "cuda:0"
  
  batch_size: 4

  num_epochs: 100
  optimizer: "AdamW"
  learning_rate: 0.0001
  weight_decay: 0.00001
  
  lr_scheduler: "CosineAnnealingLR"
  scheduler_params:
    T_max: 100
  
  loss_function: "DiceCELoss"
  loss_params:
    to_onehot_y: True
    softmax: True
    include_background: False

  # Validation Settings
  validation_interval: 1
  validation_sw_batch_size: 4
  metrics: ["MeanDice"]
  metric_params:
    include_background: False
    reduction: "mean_batch"

  # Checkpoint Settings
  checkpoint_dir: "outputs/checkpoints"
  save_best_only: False
  best_metric: "val_mean_dice"
  monitor_mode: "max"
  
# 5. Logging Settings
logging:
  log_dir: "outputs/logs"
  log_interval: 20
  use_tensorboard: True
  tensorboard_dir: "outputs/tb_logs"